# Header

menu:
  主页: /
  #相册: /photos

# SubNav
subnav:
  github: "https://github.com/manchungkali"
  #weibo: ""
  #rss: /atom.xml
  #psn: "#"
  #zhihu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:kalikong2056@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  weixin: "/assets/new/weixin.jpg"

#rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /manchungkail.github.io

# Content
excerpt_link: 'more'
show_all_link: '展开全文'
fancybox: true
mathjax: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
reward_wording: '多谢你请我饮茶'
alipay: /assets/img/alipay.jpg
weixin: /assets/img/weixinzhifu.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
#baidu_analytics: 'a30844fa2bcbce0a9e001fe06cefeddf'
google_analytics: false
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/new/kalikong.jpg

#是否开启分享
share_jia: true

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#请参考wiki：
gitalk:
  enable:  true
  githubID:  'manchungkali'   
  repo:  'manchungkali.github.io' #这里可以另开一个也可以就用你博客的那个repo
  ClientID:  '5d25deebbabfeba1e71b'
  ClientSecret:  '332f6b9e5d6bbcae04a788e9b3fa3bb38e376d8b'
  adminUser:  'manchungkali' 
  distractionFreeMode: true
  id: location.pathname
  language: zh-CN

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: '关于我'

friends:
  智汇·海川: http://gzhcrobot.com/index
  

aboutme: Kong<br>毕业于广大，就职于广州某小厂<br><br>左手情诗，右手码字，<br>目前是工业互联网开发一人<br><br>享受生活，热爱姑娘。